// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/types/change/types.proto

package change

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Phase is the phase of a NetworkChange
type Phase int32

const (
	// CHANGE indicates the change has been requested
	Phase_CHANGE Phase = 0
	// ROLLBACK indicates a rollback has been requested for the change
	Phase_ROLLBACK Phase = 1
)

var Phase_name = map[int32]string{
	0: "CHANGE",
	1: "ROLLBACK",
}

var Phase_value = map[string]int32{
	"CHANGE":   0,
	"ROLLBACK": 1,
}

func (x Phase) String() string {
	return proto.EnumName(Phase_name, int32(x))
}

func (Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12f7eaf625e420c6, []int{0}
}

// State is the state of a phase
type State int32

const (
	// PENDING indicates the phase is pending
	State_PENDING State = 0
	// RUNNING indicates the phase is in progress
	State_RUNNING State = 1
	// COMPLETE indicates the phase is complete
	State_COMPLETE State = 2
	// FAILED indicates the phase failed
	State_FAILED State = 3
)

var State_name = map[int32]string{
	0: "PENDING",
	1: "RUNNING",
	2: "COMPLETE",
	3: "FAILED",
}

var State_value = map[string]int32{
	"PENDING":  0,
	"RUNNING":  1,
	"COMPLETE": 2,
	"FAILED":   3,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12f7eaf625e420c6, []int{1}
}

// Reason is a reason for a FAILED state
type Reason int32

const (
	// UNKNOWN is a null or unknown failure reason
	Reason_UNKNOWN Reason = 0
	// ERROR indicates an error occurred when applying the change
	Reason_ERROR Reason = 1
	// UNAVAILABLE indicates the change failed due to unavailable device(s)
	Reason_UNAVAILABLE Reason = 2
)

var Reason_name = map[int32]string{
	0: "UNKNOWN",
	1: "ERROR",
	2: "UNAVAILABLE",
}

var Reason_value = map[string]int32{
	"UNKNOWN":     0,
	"ERROR":       1,
	"UNAVAILABLE": 2,
}

func (x Reason) String() string {
	return proto.EnumName(Reason_name, int32(x))
}

func (Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12f7eaf625e420c6, []int{2}
}

// Status is the status of a NetworkChange
type Status struct {
	// 'phase' is the current phase of the NetworkChange
	Phase Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=onos.config.change.Phase" json:"phase,omitempty"`
	// 'state' is the state of the change within a Phase
	State State `protobuf:"varint,2,opt,name=state,proto3,enum=onos.config.change.State" json:"state,omitempty"`
	// 'reason' is a failure reason
	Reason Reason `protobuf:"varint,3,opt,name=reason,proto3,enum=onos.config.change.Reason" json:"reason,omitempty"`
	// message is a result message
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_12f7eaf625e420c6, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return m.Size()
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_CHANGE
}

func (m *Status) GetState() State {
	if m != nil {
		return m.State
	}
	return State_PENDING
}

func (m *Status) GetReason() Reason {
	if m != nil {
		return m.Reason
	}
	return Reason_UNKNOWN
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("onos.config.change.Phase", Phase_name, Phase_value)
	proto.RegisterEnum("onos.config.change.State", State_name, State_value)
	proto.RegisterEnum("onos.config.change.Reason", Reason_name, Reason_value)
	proto.RegisterType((*Status)(nil), "onos.config.change.Status")
}

func init() { proto.RegisterFile("pkg/types/change/types.proto", fileDescriptor_12f7eaf625e420c6) }

var fileDescriptor_12f7eaf625e420c6 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xc2, 0x30,
	0x1c, 0x87, 0x57, 0x70, 0x43, 0xfe, 0x18, 0x6d, 0x7a, 0x9a, 0xc6, 0x2c, 0xe8, 0x89, 0x70, 0x18,
	0x11, 0x8f, 0x9e, 0x06, 0x54, 0x24, 0xcc, 0x8e, 0x54, 0xd1, 0x73, 0x25, 0x75, 0x18, 0xe3, 0xba,
	0xd0, 0x7a, 0xf0, 0x2d, 0x7c, 0x1c, 0x1f, 0xc1, 0x23, 0x47, 0x8f, 0x86, 0xbd, 0x88, 0xe9, 0xa6,
	0x27, 0xf5, 0xf8, 0xa5, 0xdf, 0xf7, 0xcf, 0x2f, 0x29, 0x1c, 0xe6, 0x8f, 0x69, 0xcf, 0xbc, 0xe4,
	0x52, 0xf7, 0x16, 0x4b, 0x91, 0xa5, 0xb2, 0x82, 0x30, 0x5f, 0x29, 0xa3, 0x08, 0x51, 0x99, 0xd2,
	0xe1, 0x42, 0x65, 0xf7, 0x0f, 0x69, 0x58, 0xbd, 0x1f, 0xbf, 0x21, 0xf0, 0xae, 0x8c, 0x30, 0xcf,
	0x9a, 0xf4, 0xc0, 0xcd, 0x97, 0x42, 0x4b, 0x1f, 0xb5, 0x51, 0x67, 0xb7, 0xbf, 0x1f, 0xfe, 0xd6,
	0xc3, 0x99, 0x15, 0x78, 0xe5, 0xd9, 0x40, 0x1b, 0x61, 0xa4, 0x5f, 0xfb, 0x3f, 0xb0, 0xb7, 0x25,
	0xaf, 0x3c, 0xd2, 0x07, 0x6f, 0x25, 0x85, 0x56, 0x99, 0x5f, 0x2f, 0x8b, 0x83, 0xbf, 0x0a, 0x5e,
	0x1a, 0xfc, 0xdb, 0x24, 0x3e, 0x34, 0x9e, 0xa4, 0xd6, 0x22, 0x95, 0xfe, 0x56, 0x1b, 0x75, 0x9a,
	0xfc, 0x07, 0xbb, 0x47, 0xe0, 0x96, 0x73, 0x08, 0x80, 0x37, 0xbc, 0x88, 0xd8, 0x98, 0x62, 0x87,
	0xec, 0xc0, 0x36, 0x4f, 0xe2, 0x78, 0x10, 0x0d, 0xa7, 0x18, 0x75, 0xcf, 0xc0, 0x2d, 0x07, 0x90,
	0x16, 0x34, 0x66, 0x94, 0x8d, 0x26, 0x6c, 0x8c, 0x1d, 0x0b, 0x7c, 0xce, 0x98, 0x05, 0x64, 0x83,
	0x61, 0x72, 0x39, 0x8b, 0xe9, 0x35, 0xc5, 0x35, 0x7b, 0xea, 0x3c, 0x9a, 0xc4, 0x74, 0x84, 0xeb,
	0xdd, 0x13, 0xf0, 0xaa, 0x2d, 0x36, 0x98, 0xb3, 0x29, 0x4b, 0x6e, 0x19, 0x76, 0x48, 0x13, 0x5c,
	0xca, 0x79, 0xc2, 0x31, 0x22, 0x7b, 0xd0, 0x9a, 0xb3, 0xe8, 0x26, 0x9a, 0xc4, 0xd1, 0x20, 0xa6,
	0xb8, 0x36, 0xf0, 0xdf, 0x37, 0x01, 0x5a, 0x6f, 0x02, 0xf4, 0xb9, 0x09, 0xd0, 0x6b, 0x11, 0x38,
	0xeb, 0x22, 0x70, 0x3e, 0x8a, 0xc0, 0xb9, 0xf3, 0xca, 0x2f, 0x38, 0xfd, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x1a, 0x34, 0x99, 0x3e, 0xa2, 0x01, 0x00, 0x00,
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x22
	}
	if m.Reason != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x18
	}
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	if m.Phase != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Phase != 0 {
		n += 1 + sovTypes(uint64(m.Phase))
	}
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	if m.Reason != 0 {
		n += 1 + sovTypes(uint64(m.Reason))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= Phase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= Reason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthTypes
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTypes(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthTypes
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTypes = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes   = fmt.Errorf("proto: integer overflow")
)
