// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/northbound/admin/admin.proto

// Package admin defines the administrative gRPC interfaces.

package admin

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	device "github.com/onosproject/onos-config/pkg/types/change/device"
	device1 "github.com/onosproject/onos-config/pkg/types/snapshot/device"
	github_com_onosproject_onos_topo_pkg_northbound_device "github.com/onosproject/onos-topo/pkg/northbound/device"
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Streaming event type
type Type int32

const (
	// NONE indicates this response does not represent a state change
	Type_NONE Type = 0
	// ADDED is an event which occurs when an item is added
	Type_ADDED Type = 1
	// UPDATED is an event which occurs when an item is updated
	Type_UPDATED Type = 2
	// REMOVED is an event which occurs when an item is removed
	Type_REMOVED Type = 3
)

var Type_name = map[int32]string{
	0: "NONE",
	1: "ADDED",
	2: "UPDATED",
	3: "REMOVED",
}

var Type_value = map[string]int32{
	"NONE":    0,
	"ADDED":   1,
	"UPDATED": 2,
	"REMOVED": 3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{0}
}

// NetworkChangesRequest is a message for specifying GetNetworkChanges query parameters.
type NetworkChangesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkChangesRequest) Reset()         { *m = NetworkChangesRequest{} }
func (m *NetworkChangesRequest) String() string { return proto.CompactTextString(m) }
func (*NetworkChangesRequest) ProtoMessage()    {}
func (*NetworkChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{0}
}
func (m *NetworkChangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkChangesRequest.Unmarshal(m, b)
}
func (m *NetworkChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkChangesRequest.Marshal(b, m, deterministic)
}
func (m *NetworkChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkChangesRequest.Merge(m, src)
}
func (m *NetworkChangesRequest) XXX_Size() int {
	return xxx_messageInfo_NetworkChangesRequest.Size(m)
}
func (m *NetworkChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkChangesRequest proto.InternalMessageInfo

// ConfigChange is a descriptor of a submitted configuration change targeted as a single device.
type ConfigChange struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigChange) Reset()         { *m = ConfigChange{} }
func (m *ConfigChange) String() string { return proto.CompactTextString(m) }
func (*ConfigChange) ProtoMessage()    {}
func (*ConfigChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{1}
}
func (m *ConfigChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigChange.Unmarshal(m, b)
}
func (m *ConfigChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigChange.Marshal(b, m, deterministic)
}
func (m *ConfigChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigChange.Merge(m, src)
}
func (m *ConfigChange) XXX_Size() int {
	return xxx_messageInfo_ConfigChange.Size(m)
}
func (m *ConfigChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigChange.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigChange proto.InternalMessageInfo

func (m *ConfigChange) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigChange) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Change is a descriptor of a submitted configuration change targeted at a single device.
type Change struct {
	//    option deprecated = true; Commented out for the moment - breaks static check
	Time                 *time.Time            `protobuf:"bytes,1,opt,name=time,proto3,stdtime" json:"time,omitempty"`
	Id                   string                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 string                `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	ChangeValues         []*device.ChangeValue `protobuf:"bytes,4,rep,name=change_values,json=changeValues,proto3" json:"change_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{2}
}
func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetTime() *time.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Change) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Change) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Change) GetChangeValues() []*device.ChangeValue {
	if m != nil {
		return m.ChangeValues
	}
	return nil
}

// NetChange is a descriptor of a configuration change submitted via gNMI.
type NetChange struct {
	//    option deprecated = true; Commented out for the moment - breaks static check
	Time                 *time.Time      `protobuf:"bytes,1,opt,name=time,proto3,stdtime" json:"time,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User                 string          `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Changes              []*ConfigChange `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NetChange) Reset()         { *m = NetChange{} }
func (m *NetChange) String() string { return proto.CompactTextString(m) }
func (*NetChange) ProtoMessage()    {}
func (*NetChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{3}
}
func (m *NetChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetChange.Unmarshal(m, b)
}
func (m *NetChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetChange.Marshal(b, m, deterministic)
}
func (m *NetChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetChange.Merge(m, src)
}
func (m *NetChange) XXX_Size() int {
	return xxx_messageInfo_NetChange.Size(m)
}
func (m *NetChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NetChange.DiscardUnknown(m)
}

var xxx_messageInfo_NetChange proto.InternalMessageInfo

func (m *NetChange) GetTime() *time.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *NetChange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetChange) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *NetChange) GetChanges() []*ConfigChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

type ReadOnlySubPath struct {
	SubPath              string           `protobuf:"bytes,1,opt,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	ValueType            device.ValueType `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=onos.config.change.device.ValueType" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadOnlySubPath) Reset()         { *m = ReadOnlySubPath{} }
func (m *ReadOnlySubPath) String() string { return proto.CompactTextString(m) }
func (*ReadOnlySubPath) ProtoMessage()    {}
func (*ReadOnlySubPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{4}
}
func (m *ReadOnlySubPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOnlySubPath.Unmarshal(m, b)
}
func (m *ReadOnlySubPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOnlySubPath.Marshal(b, m, deterministic)
}
func (m *ReadOnlySubPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOnlySubPath.Merge(m, src)
}
func (m *ReadOnlySubPath) XXX_Size() int {
	return xxx_messageInfo_ReadOnlySubPath.Size(m)
}
func (m *ReadOnlySubPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOnlySubPath.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOnlySubPath proto.InternalMessageInfo

func (m *ReadOnlySubPath) GetSubPath() string {
	if m != nil {
		return m.SubPath
	}
	return ""
}

func (m *ReadOnlySubPath) GetValueType() device.ValueType {
	if m != nil {
		return m.ValueType
	}
	return device.ValueType_EMPTY
}

type ReadOnlyPath struct {
	Path                 string             `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SubPath              []*ReadOnlySubPath `protobuf:"bytes,2,rep,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReadOnlyPath) Reset()         { *m = ReadOnlyPath{} }
func (m *ReadOnlyPath) String() string { return proto.CompactTextString(m) }
func (*ReadOnlyPath) ProtoMessage()    {}
func (*ReadOnlyPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{5}
}
func (m *ReadOnlyPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOnlyPath.Unmarshal(m, b)
}
func (m *ReadOnlyPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOnlyPath.Marshal(b, m, deterministic)
}
func (m *ReadOnlyPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOnlyPath.Merge(m, src)
}
func (m *ReadOnlyPath) XXX_Size() int {
	return xxx_messageInfo_ReadOnlyPath.Size(m)
}
func (m *ReadOnlyPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOnlyPath.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOnlyPath proto.InternalMessageInfo

func (m *ReadOnlyPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadOnlyPath) GetSubPath() []*ReadOnlySubPath {
	if m != nil {
		return m.SubPath
	}
	return nil
}

type ReadWritePath struct {
	Path                 string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ValueType            device.ValueType `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=onos.config.change.device.ValueType" json:"value_type,omitempty"`
	Units                string           `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	Description          string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Mandatory            bool             `protobuf:"varint,5,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Default              string           `protobuf:"bytes,6,opt,name=default,proto3" json:"default,omitempty"`
	Range                []string         `protobuf:"bytes,7,rep,name=range,proto3" json:"range,omitempty"`
	Length               []string         `protobuf:"bytes,8,rep,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadWritePath) Reset()         { *m = ReadWritePath{} }
func (m *ReadWritePath) String() string { return proto.CompactTextString(m) }
func (*ReadWritePath) ProtoMessage()    {}
func (*ReadWritePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{6}
}
func (m *ReadWritePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadWritePath.Unmarshal(m, b)
}
func (m *ReadWritePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadWritePath.Marshal(b, m, deterministic)
}
func (m *ReadWritePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadWritePath.Merge(m, src)
}
func (m *ReadWritePath) XXX_Size() int {
	return xxx_messageInfo_ReadWritePath.Size(m)
}
func (m *ReadWritePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadWritePath.DiscardUnknown(m)
}

var xxx_messageInfo_ReadWritePath proto.InternalMessageInfo

func (m *ReadWritePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadWritePath) GetValueType() device.ValueType {
	if m != nil {
		return m.ValueType
	}
	return device.ValueType_EMPTY
}

func (m *ReadWritePath) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

func (m *ReadWritePath) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ReadWritePath) GetMandatory() bool {
	if m != nil {
		return m.Mandatory
	}
	return false
}

func (m *ReadWritePath) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *ReadWritePath) GetRange() []string {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *ReadWritePath) GetLength() []string {
	if m != nil {
		return m.Length
	}
	return nil
}

type ModelInfo struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelData            []*gnmi.ModelData `protobuf:"bytes,3,rep,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`
	Module               string            `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	GetStateMode         uint32            `protobuf:"varint,5,opt,name=getStateMode,proto3" json:"getStateMode,omitempty"`
	ReadOnlyPath         []*ReadOnlyPath   `protobuf:"bytes,7,rep,name=read_only_path,json=readOnlyPath,proto3" json:"read_only_path,omitempty"`
	ReadWritePath        []*ReadWritePath  `protobuf:"bytes,8,rep,name=read_write_path,json=readWritePath,proto3" json:"read_write_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModelInfo) Reset()         { *m = ModelInfo{} }
func (m *ModelInfo) String() string { return proto.CompactTextString(m) }
func (*ModelInfo) ProtoMessage()    {}
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{7}
}
func (m *ModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInfo.Unmarshal(m, b)
}
func (m *ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInfo.Marshal(b, m, deterministic)
}
func (m *ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfo.Merge(m, src)
}
func (m *ModelInfo) XXX_Size() int {
	return xxx_messageInfo_ModelInfo.Size(m)
}
func (m *ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfo proto.InternalMessageInfo

func (m *ModelInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ModelInfo) GetModelData() []*gnmi.ModelData {
	if m != nil {
		return m.ModelData
	}
	return nil
}

func (m *ModelInfo) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *ModelInfo) GetGetStateMode() uint32 {
	if m != nil {
		return m.GetStateMode
	}
	return 0
}

func (m *ModelInfo) GetReadOnlyPath() []*ReadOnlyPath {
	if m != nil {
		return m.ReadOnlyPath
	}
	return nil
}

func (m *ModelInfo) GetReadWritePath() []*ReadWritePath {
	if m != nil {
		return m.ReadWritePath
	}
	return nil
}

// Chunk is for streaming a model plugin file to the server
// There is a built in limit in gRPC of 4MB - plugin is usually around 20MB
// so break in to chunks of approx 1MB
type Chunk struct {
	SoFile               string   `protobuf:"bytes,1,opt,name=so_file,json=soFile,proto3" json:"so_file,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{8}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetSoFile() string {
	if m != nil {
		return m.SoFile
	}
	return ""
}

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// RegisterRequest carries data for registering a YANG model.
type RegisterRequest struct {
	// Full path and filename of a shared object library as a model plugin
	SoFile               string   `protobuf:"bytes,1,opt,name=so_file,json=soFile,proto3" json:"so_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{9}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSoFile() string {
	if m != nil {
		return m.SoFile
	}
	return ""
}

type SchemaEntry struct {
	SchemaPath           string   `protobuf:"bytes,1,opt,name=schema_path,json=schemaPath,proto3" json:"schema_path,omitempty"`
	SchemaJson           string   `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaEntry) Reset()         { *m = SchemaEntry{} }
func (m *SchemaEntry) String() string { return proto.CompactTextString(m) }
func (*SchemaEntry) ProtoMessage()    {}
func (*SchemaEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{10}
}
func (m *SchemaEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaEntry.Unmarshal(m, b)
}
func (m *SchemaEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaEntry.Marshal(b, m, deterministic)
}
func (m *SchemaEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaEntry.Merge(m, src)
}
func (m *SchemaEntry) XXX_Size() int {
	return xxx_messageInfo_SchemaEntry.Size(m)
}
func (m *SchemaEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaEntry proto.InternalMessageInfo

func (m *SchemaEntry) GetSchemaPath() string {
	if m != nil {
		return m.SchemaPath
	}
	return ""
}

func (m *SchemaEntry) GetSchemaJson() string {
	if m != nil {
		return m.SchemaJson
	}
	return ""
}

// RegisterResponse carries status of YANG model registration.
type RegisterResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{11}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// ListModelsRequest carries data for querying registered models.
type ListModelsRequest struct {
	Verbose              bool     `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	ModelName            string   `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion         string   `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{12}
}
func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

func (m *ListModelsRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *ListModelsRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *ListModelsRequest) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

// RollbackRequest carries the name of a network config to rollback. If there
// are subsequent changes to any of the devices in that config, the rollback will
// be rejected. If no name is given the last network change will be rolled back.
type RollbackRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRequest) Reset()         { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()    {}
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{13}
}
func (m *RollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRequest.Unmarshal(m, b)
}
func (m *RollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRequest.Marshal(b, m, deterministic)
}
func (m *RollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRequest.Merge(m, src)
}
func (m *RollbackRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackRequest.Size(m)
}
func (m *RollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRequest proto.InternalMessageInfo

func (m *RollbackRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RollbackRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type RollbackResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackResponse) Reset()         { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()    {}
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{14}
}
func (m *RollbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackResponse.Unmarshal(m, b)
}
func (m *RollbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackResponse.Marshal(b, m, deterministic)
}
func (m *RollbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackResponse.Merge(m, src)
}
func (m *RollbackResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackResponse.Size(m)
}
func (m *RollbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackResponse proto.InternalMessageInfo

func (m *RollbackResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetSnapshotRequest gets a snapshot
type GetSnapshotRequest struct {
	DeviceID             github_com_onosproject_onos_topo_pkg_northbound_device.ID `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3,casttype=github.com/onosproject/onos-topo/pkg/northbound/device.ID" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *GetSnapshotRequest) Reset()         { *m = GetSnapshotRequest{} }
func (m *GetSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotRequest) ProtoMessage()    {}
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{15}
}
func (m *GetSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotRequest.Unmarshal(m, b)
}
func (m *GetSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *GetSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotRequest.Merge(m, src)
}
func (m *GetSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotRequest.Size(m)
}
func (m *GetSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotRequest proto.InternalMessageInfo

func (m *GetSnapshotRequest) GetDeviceID() github_com_onosproject_onos_topo_pkg_northbound_device.ID {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

// ListSnapshotsRequest requests a list of snapshots
type ListSnapshotsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSnapshotsRequest) Reset()         { *m = ListSnapshotsRequest{} }
func (m *ListSnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSnapshotsRequest) ProtoMessage()    {}
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{16}
}
func (m *ListSnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSnapshotsRequest.Unmarshal(m, b)
}
func (m *ListSnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *ListSnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSnapshotsRequest.Merge(m, src)
}
func (m *ListSnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSnapshotsRequest.Size(m)
}
func (m *ListSnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSnapshotsRequest proto.InternalMessageInfo

// CompactChangesRequest requests a compaction of the change stores
type CompactChangesRequest struct {
	RetentionPeriod      *time.Duration `protobuf:"bytes,1,opt,name=retention_period,json=retentionPeriod,proto3,stdduration" json:"retention_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CompactChangesRequest) Reset()         { *m = CompactChangesRequest{} }
func (m *CompactChangesRequest) String() string { return proto.CompactTextString(m) }
func (*CompactChangesRequest) ProtoMessage()    {}
func (*CompactChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{17}
}
func (m *CompactChangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactChangesRequest.Unmarshal(m, b)
}
func (m *CompactChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactChangesRequest.Marshal(b, m, deterministic)
}
func (m *CompactChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactChangesRequest.Merge(m, src)
}
func (m *CompactChangesRequest) XXX_Size() int {
	return xxx_messageInfo_CompactChangesRequest.Size(m)
}
func (m *CompactChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompactChangesRequest proto.InternalMessageInfo

func (m *CompactChangesRequest) GetRetentionPeriod() *time.Duration {
	if m != nil {
		return m.RetentionPeriod
	}
	return nil
}

// CompactChangesResponse is a compact response
type CompactChangesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactChangesResponse) Reset()         { *m = CompactChangesResponse{} }
func (m *CompactChangesResponse) String() string { return proto.CompactTextString(m) }
func (*CompactChangesResponse) ProtoMessage()    {}
func (*CompactChangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{18}
}
func (m *CompactChangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactChangesResponse.Unmarshal(m, b)
}
func (m *CompactChangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactChangesResponse.Marshal(b, m, deterministic)
}
func (m *CompactChangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactChangesResponse.Merge(m, src)
}
func (m *CompactChangesResponse) XXX_Size() int {
	return xxx_messageInfo_CompactChangesResponse.Size(m)
}
func (m *CompactChangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactChangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompactChangesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("onos.config.admin.Type", Type_name, Type_value)
	proto.RegisterType((*NetworkChangesRequest)(nil), "onos.config.admin.NetworkChangesRequest")
	proto.RegisterType((*ConfigChange)(nil), "onos.config.admin.ConfigChange")
	proto.RegisterType((*Change)(nil), "onos.config.admin.Change")
	proto.RegisterType((*NetChange)(nil), "onos.config.admin.NetChange")
	proto.RegisterType((*ReadOnlySubPath)(nil), "onos.config.admin.ReadOnlySubPath")
	proto.RegisterType((*ReadOnlyPath)(nil), "onos.config.admin.ReadOnlyPath")
	proto.RegisterType((*ReadWritePath)(nil), "onos.config.admin.ReadWritePath")
	proto.RegisterType((*ModelInfo)(nil), "onos.config.admin.ModelInfo")
	proto.RegisterType((*Chunk)(nil), "onos.config.admin.Chunk")
	proto.RegisterType((*RegisterRequest)(nil), "onos.config.admin.RegisterRequest")
	proto.RegisterType((*SchemaEntry)(nil), "onos.config.admin.SchemaEntry")
	proto.RegisterType((*RegisterResponse)(nil), "onos.config.admin.RegisterResponse")
	proto.RegisterType((*ListModelsRequest)(nil), "onos.config.admin.ListModelsRequest")
	proto.RegisterType((*RollbackRequest)(nil), "onos.config.admin.RollbackRequest")
	proto.RegisterType((*RollbackResponse)(nil), "onos.config.admin.RollbackResponse")
	proto.RegisterType((*GetSnapshotRequest)(nil), "onos.config.admin.GetSnapshotRequest")
	proto.RegisterType((*ListSnapshotsRequest)(nil), "onos.config.admin.ListSnapshotsRequest")
	proto.RegisterType((*CompactChangesRequest)(nil), "onos.config.admin.CompactChangesRequest")
	proto.RegisterType((*CompactChangesResponse)(nil), "onos.config.admin.CompactChangesResponse")
}

func init() { proto.RegisterFile("pkg/northbound/admin/admin.proto", fileDescriptor_9081d84c442224d8) }

var fileDescriptor_9081d84c442224d8 = []byte{
	// 1231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xff, 0xda, 0x71, 0x62, 0xfb, 0xd9, 0x49, 0xdc, 0xf9, 0xf6, 0xc7, 0xd6, 0x2a, 0xc4, 0xda,
	0x16, 0x08, 0x15, 0xac, 0xa3, 0x00, 0x87, 0x22, 0x21, 0x68, 0x63, 0xb7, 0x4d, 0xa1, 0x49, 0xb5,
	0x69, 0x03, 0x12, 0x20, 0x33, 0xf6, 0x4e, 0xd6, 0xdb, 0xec, 0xce, 0x6c, 0x77, 0x66, 0x53, 0x45,
	0xe2, 0xcc, 0x89, 0x03, 0x47, 0xfe, 0x00, 0xee, 0xdc, 0xf8, 0x73, 0x8a, 0xc4, 0x9f, 0xc1, 0x09,
	0xcd, 0x2f, 0x67, 0x9d, 0x6c, 0xaa, 0x54, 0x70, 0x59, 0xbd, 0xf7, 0xf6, 0xfd, 0x9a, 0xcf, 0x7b,
	0x6f, 0xde, 0x40, 0x2f, 0x3d, 0x0c, 0xfb, 0x94, 0x65, 0x62, 0x3a, 0x66, 0x39, 0x0d, 0xfa, 0x38,
	0x48, 0x22, 0xaa, 0xbf, 0x5e, 0x9a, 0x31, 0xc1, 0xd0, 0x25, 0x46, 0x19, 0xf7, 0x26, 0x8c, 0x1e,
	0x44, 0xa1, 0xa7, 0x7e, 0x74, 0xd7, 0x42, 0xc6, 0xc2, 0x98, 0xf4, 0x95, 0xc2, 0x38, 0x3f, 0xe8,
	0x8b, 0x28, 0x21, 0x5c, 0xe0, 0x24, 0xd5, 0x36, 0xdd, 0xb7, 0x4f, 0x2b, 0x04, 0x79, 0x86, 0x45,
	0xc4, 0x8c, 0xcf, 0xee, 0xe5, 0x90, 0x85, 0x4c, 0x91, 0x7d, 0x49, 0x19, 0xe9, 0x46, 0x18, 0x89,
	0x69, 0x3e, 0xf6, 0x26, 0x2c, 0xe9, 0xb3, 0x94, 0x50, 0x1d, 0xb3, 0x1f, 0xd2, 0x24, 0xea, 0x1b,
	0x65, 0x49, 0xca, 0x8f, 0xb1, 0xb8, 0x5f, 0xb4, 0xa0, 0x8c, 0xa7, 0x19, 0x7b, 0x4e, 0x26, 0x42,
	0xd1, 0x1f, 0x1a, 0x73, 0x79, 0x40, 0x71, 0x9c, 0x12, 0xde, 0x9f, 0x4c, 0x31, 0x0d, 0x49, 0x3f,
	0x20, 0x47, 0xd1, 0x84, 0x68, 0x99, 0xf1, 0xf3, 0xf0, 0x8d, 0xfc, 0x70, 0x8a, 0x53, 0x3e, 0x65,
	0xa2, 0xc4, 0x93, 0x7b, 0x0d, 0xae, 0xec, 0x10, 0xf1, 0x92, 0x65, 0x87, 0x5b, 0x2a, 0x1a, 0xf7,
	0xc9, 0x8b, 0x9c, 0x70, 0xe1, 0x6e, 0x42, 0x7b, 0x4b, 0x39, 0xd2, 0x72, 0xb4, 0x02, 0xd5, 0x28,
	0x70, 0x2a, 0xbd, 0xca, 0x7a, 0xd3, 0xaf, 0x46, 0x01, 0x42, 0x50, 0x9b, 0x62, 0x3e, 0x75, 0xaa,
	0x4a, 0xa2, 0x68, 0xf7, 0xf7, 0x0a, 0x2c, 0x19, 0xf5, 0x8f, 0xa1, 0x26, 0x41, 0x56, 0x06, 0xad,
	0xcd, 0xae, 0xa7, 0x01, 0xf6, 0x2c, 0xc0, 0xde, 0x53, 0x5b, 0x81, 0x7b, 0xb5, 0x5f, 0xfe, 0x5c,
	0xab, 0xf8, 0x4a, 0xdb, 0x04, 0xa9, 0x16, 0x83, 0x04, 0x84, 0x4f, 0x9c, 0x05, 0x1d, 0x44, 0xd2,
	0xe8, 0x4b, 0x58, 0xd6, 0xc0, 0x8c, 0x8e, 0x70, 0x9c, 0x13, 0xee, 0xd4, 0x7a, 0x0b, 0xeb, 0xad,
	0xcd, 0x77, 0xbd, 0x62, 0xdd, 0xb5, 0x86, 0xa7, 0x0f, 0xec, 0xe9, 0x9c, 0xf6, 0xa5, 0xba, 0xdf,
	0x9e, 0x9c, 0x30, 0xdc, 0xfd, 0xad, 0x02, 0xcd, 0x1d, 0x22, 0xfe, 0x55, 0xd2, 0x08, 0x6a, 0x14,
	0x27, 0xc4, 0x22, 0x21, 0x69, 0x29, 0xcb, 0x39, 0xc9, 0x6c, 0xe2, 0x92, 0x46, 0x77, 0xa0, 0xae,
	0x63, 0xdb, 0x94, 0xd7, 0xbc, 0x33, 0xad, 0xea, 0x15, 0x31, 0xf7, 0xad, 0xbe, 0xfb, 0x02, 0x56,
	0x7d, 0x82, 0x83, 0x5d, 0x1a, 0x1f, 0xef, 0xe5, 0xe3, 0x27, 0x58, 0x4c, 0xd1, 0x75, 0x68, 0xf0,
	0x7c, 0x3c, 0x4a, 0xb1, 0x98, 0x9a, 0xaa, 0xd4, 0xb9, 0xf9, 0xb5, 0x05, 0xa0, 0xa0, 0x19, 0xc9,
	0x42, 0xab, 0xb4, 0x56, 0x36, 0x6f, 0xbd, 0x06, 0x1e, 0x85, 0xc5, 0xd3, 0xe3, 0x94, 0xf8, 0xcd,
	0x23, 0x4b, 0xba, 0x18, 0xda, 0x36, 0xa4, 0x72, 0x8a, 0xa0, 0x56, 0x88, 0xa5, 0x68, 0xf4, 0x59,
	0x21, 0x87, 0xaa, 0x3a, 0x92, 0x5b, 0x72, 0xa4, 0x53, 0x99, 0xcf, 0xf2, 0x74, 0x7f, 0xaa, 0xc2,
	0xb2, 0xfc, 0xf9, 0x75, 0x16, 0x09, 0x72, 0x6e, 0x90, 0xff, 0xe2, 0x34, 0xe8, 0x32, 0x2c, 0xe6,
	0x34, 0x12, 0xdc, 0x14, 0x44, 0x33, 0xa8, 0x07, 0x2d, 0xd9, 0x52, 0x59, 0x94, 0xca, 0x59, 0x77,
	0x6a, 0xea, 0x5f, 0x51, 0x84, 0x6e, 0x40, 0x33, 0xc1, 0x34, 0xc0, 0x82, 0x65, 0xc7, 0xce, 0x62,
	0xaf, 0xb2, 0xde, 0xf0, 0x4f, 0x04, 0xc8, 0x81, 0x7a, 0x40, 0x0e, 0x70, 0x1e, 0x0b, 0x67, 0x49,
	0x97, 0xc0, 0xb0, 0x32, 0x5e, 0x26, 0x93, 0x72, 0xea, 0xbd, 0x05, 0x19, 0x4f, 0x31, 0xe8, 0x2a,
	0x2c, 0xc5, 0x84, 0x86, 0x62, 0xea, 0x34, 0x94, 0xd8, 0x70, 0xee, 0x1f, 0x55, 0x68, 0x3e, 0x66,
	0x01, 0x89, 0xb7, 0xe9, 0x01, 0x9b, 0xf5, 0x53, 0xa5, 0xd0, 0x4f, 0x0e, 0xd4, 0x8f, 0x48, 0xc6,
	0x65, 0x96, 0xba, 0xcd, 0x2c, 0x8b, 0x3c, 0x80, 0x44, 0x9a, 0x8e, 0x02, 0x2c, 0xb0, 0xb3, 0xa0,
	0xaa, 0xb0, 0xea, 0xa9, 0x3b, 0x47, 0xb9, 0x1c, 0x60, 0x81, 0xfd, 0x66, 0x62, 0x49, 0x99, 0x43,
	0xc2, 0x82, 0x3c, 0x26, 0xe6, 0xb8, 0x86, 0x43, 0x2e, 0xb4, 0x43, 0x22, 0xf6, 0x04, 0x16, 0x44,
	0xda, 0xa9, 0xc3, 0x2e, 0xfb, 0x73, 0x32, 0x34, 0x84, 0x95, 0x8c, 0xe0, 0x60, 0xc4, 0x68, 0x7c,
	0xac, 0xab, 0x5e, 0x3f, 0xb7, 0x91, 0x8b, 0xcd, 0xe3, 0xb7, 0xb3, 0x62, 0x2b, 0x3d, 0x84, 0x55,
	0xe5, 0xe6, 0xa5, 0xac, 0xbb, 0xf6, 0xd3, 0x50, 0x7e, 0x7a, 0xe7, 0xf8, 0x99, 0x35, 0x88, 0xbf,
	0x9c, 0x15, 0x59, 0xf7, 0x53, 0x58, 0xdc, 0x9a, 0xe6, 0xf4, 0x10, 0x5d, 0x83, 0x3a, 0x67, 0xa3,
	0x83, 0x28, 0xb6, 0xb0, 0x2d, 0x71, 0x76, 0x3f, 0x8a, 0x15, 0x70, 0x5b, 0x8c, 0x0a, 0x42, 0x85,
	0x02, 0xae, 0xed, 0x5b, 0xd6, 0xbd, 0x2d, 0x67, 0x2a, 0x8c, 0xb8, 0x20, 0x99, 0xb9, 0xf3, 0xce,
	0xf5, 0xe2, 0xee, 0x42, 0x6b, 0x6f, 0x32, 0x25, 0x09, 0x1e, 0x52, 0x91, 0x1d, 0xa3, 0x35, 0x68,
	0x71, 0xc5, 0x16, 0xc7, 0x0f, 0xb4, 0x48, 0x9d, 0xf0, 0x44, 0xe1, 0x39, 0x9f, 0x95, 0xcc, 0x28,
	0x3c, 0xe2, 0x8c, 0xba, 0x5f, 0x40, 0xe7, 0x24, 0x38, 0x4f, 0x19, 0xe5, 0xe4, 0xcd, 0xea, 0xee,
	0xbe, 0x80, 0x4b, 0x5f, 0x45, 0x5c, 0xa8, 0x1a, 0xdb, 0x4b, 0xdb, 0xa8, 0x8f, 0x19, 0xd7, 0x5e,
	0x1a, 0xbe, 0x65, 0xd1, 0x5b, 0xb6, 0x4d, 0x0a, 0x57, 0x95, 0xee, 0x8a, 0x1d, 0x19, 0xe7, 0x26,
	0x2c, 0xeb, 0xdf, 0x36, 0x9a, 0x9e, 0x93, 0xb6, 0x12, 0xee, 0x9b, 0x90, 0x9f, 0xc3, 0xaa, 0xcf,
	0xe2, 0x78, 0x8c, 0x27, 0x87, 0x36, 0xe0, 0x39, 0x39, 0x4f, 0x58, 0x92, 0x58, 0xc8, 0x9b, 0xbe,
	0x65, 0xdd, 0x0f, 0xa0, 0x73, 0xe2, 0xc0, 0x9c, 0xda, 0x81, 0x7a, 0x42, 0x38, 0xc7, 0xa1, 0x75,
	0x62, 0x59, 0xf7, 0x47, 0x40, 0x0f, 0x88, 0xd8, 0x33, 0xcb, 0xcb, 0x46, 0x3c, 0x80, 0xa6, 0x1e,
	0xf4, 0x91, 0x5d, 0x47, 0xf7, 0xb6, 0xff, 0x7a, 0xb5, 0xd6, 0x18, 0x28, 0xe1, 0xf6, 0xe0, 0xef,
	0x57, 0x6b, 0x77, 0x5e, 0xb7, 0x1d, 0x05, 0x4b, 0x59, 0xff, 0xd4, 0x23, 0xc2, 0xdc, 0x1c, 0xdb,
	0x03, 0xbf, 0xa1, 0xc9, 0xed, 0xc0, 0xbd, 0x0a, 0x97, 0x25, 0xbe, 0x36, 0xfc, 0x6c, 0x2f, 0x4e,
	0xe0, 0xca, 0x16, 0x4b, 0x52, 0x3c, 0x11, 0xf3, 0x0b, 0x13, 0x3d, 0x82, 0x4e, 0x46, 0x64, 0x67,
	0x45, 0x8c, 0x8e, 0x52, 0x92, 0x45, 0x2c, 0x30, 0x8b, 0xe4, 0xfa, 0x99, 0x45, 0x32, 0x30, 0xcf,
	0x8b, 0x7b, 0xb5, 0x5f, 0xe5, 0x1e, 0x59, 0x9d, 0x19, 0x3e, 0x51, 0x76, 0xae, 0x03, 0x57, 0x4f,
	0x07, 0xd1, 0x70, 0xdd, 0xfe, 0x04, 0x6a, 0xea, 0x42, 0x6b, 0x40, 0x6d, 0x67, 0x77, 0x67, 0xd8,
	0xf9, 0x1f, 0x6a, 0xc2, 0xe2, 0xdd, 0xc1, 0x60, 0x38, 0xe8, 0x54, 0x50, 0x0b, 0xea, 0xcf, 0x9e,
	0x0c, 0xee, 0x3e, 0x1d, 0x0e, 0x3a, 0x55, 0xc9, 0xf8, 0xc3, 0xc7, 0xbb, 0xfb, 0xc3, 0x41, 0x67,
	0x61, 0xf3, 0xe7, 0x25, 0x40, 0x7a, 0xb5, 0xdc, 0x95, 0x53, 0xb5, 0x47, 0x32, 0x79, 0x4c, 0xf4,
	0x8d, 0xbc, 0x80, 0x75, 0x1b, 0xaa, 0x46, 0x42, 0xe5, 0xf7, 0xf7, 0xdc, 0x94, 0x74, 0x6f, 0xbe,
	0x56, 0xc7, 0x94, 0x75, 0x1f, 0xfe, 0xff, 0x2c, 0x8d, 0x19, 0x0e, 0xe6, 0xfd, 0x3b, 0x65, 0x2b,
	0x4f, 0x4e, 0xf0, 0x85, 0xbc, 0xae, 0x57, 0xd0, 0x77, 0xba, 0x2c, 0xf6, 0x0f, 0x09, 0xf4, 0x00,
	0xa0, 0x5b, 0x25, 0xe6, 0x67, 0xe6, 0xa3, 0x7b, 0xa3, 0x44, 0x6b, 0x76, 0xf1, 0x6e, 0x54, 0xd0,
	0xf7, 0x70, 0xe9, 0x01, 0x11, 0xf3, 0x0f, 0x22, 0xb4, 0x5e, 0x62, 0x54, 0xfa, 0x66, 0x2a, 0x75,
	0x3f, 0x7b, 0x5d, 0x6c, 0x54, 0xd0, 0x0f, 0x70, 0xc5, 0xf6, 0xff, 0x9c, 0x83, 0x72, 0xd8, 0xe7,
	0x47, 0xad, 0x1c, 0xa0, 0xd3, 0xd3, 0xf4, 0x2d, 0xb4, 0x0a, 0x33, 0x83, 0xde, 0x29, 0xb1, 0x39,
	0x3b, 0x53, 0xdd, 0x79, 0x35, 0xfb, 0x5c, 0xb4, 0x0b, 0x75, 0xe6, 0x0d, 0xc3, 0xf2, 0xdc, 0x48,
	0xa0, 0xf7, 0xce, 0x01, 0xfd, 0xf4, 0xd0, 0x5c, 0x30, 0xc0, 0x46, 0x05, 0x11, 0x58, 0x99, 0x6f,
	0xfc, 0x52, 0xf4, 0x4b, 0x07, 0xb0, 0xfb, 0xfe, 0x05, 0x34, 0x35, 0x4c, 0xe3, 0x25, 0x35, 0x89,
	0x1f, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xde, 0x6b, 0x82, 0xd3, 0x4e, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigAdminServiceClient is the client API for ConfigAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigAdminServiceClient interface {
	// RegisterModel adds the specified YANG model to the list of supported models.
	// There is no unregister because once loaded plugins cannot be unloaded
	RegisterModel(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// UploadRegisterModel uploads and adds the model plugin to the list of supported models.
	UploadRegisterModel(ctx context.Context, opts ...grpc.CallOption) (ConfigAdminService_UploadRegisterModelClient, error)
	// ListRegisteredModels returns a stream of registered models.
	ListRegisteredModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (ConfigAdminService_ListRegisteredModelsClient, error)
	// GetNetworkChanges returns a stream of network changes submitted via gNMI.
	GetNetworkChanges(ctx context.Context, in *NetworkChangesRequest, opts ...grpc.CallOption) (ConfigAdminService_GetNetworkChangesClient, error)
	// RollbackNetworkChange rolls back the specified network change (or the latest one).
	RollbackNetworkChange(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// GetSnapshot gets a snapshot
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*device1.Snapshot, error)
	// ListSnapshots gets a list of snapshots
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (ConfigAdminService_ListSnapshotsClient, error)
	// CompactChanges requests a snapshot of NetworkChange and DeviceChange stores
	CompactChanges(ctx context.Context, in *CompactChangesRequest, opts ...grpc.CallOption) (*CompactChangesResponse, error)
}

type configAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigAdminServiceClient(cc *grpc.ClientConn) ConfigAdminServiceClient {
	return &configAdminServiceClient{cc}
}

func (c *configAdminServiceClient) RegisterModel(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/onos.config.admin.ConfigAdminService/RegisterModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAdminServiceClient) UploadRegisterModel(ctx context.Context, opts ...grpc.CallOption) (ConfigAdminService_UploadRegisterModelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[0], "/onos.config.admin.ConfigAdminService/UploadRegisterModel", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceUploadRegisterModelClient{stream}
	return x, nil
}

type ConfigAdminService_UploadRegisterModelClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*RegisterResponse, error)
	grpc.ClientStream
}

type configAdminServiceUploadRegisterModelClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceUploadRegisterModelClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *configAdminServiceUploadRegisterModelClient) CloseAndRecv() (*RegisterResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RegisterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) ListRegisteredModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (ConfigAdminService_ListRegisteredModelsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[1], "/onos.config.admin.ConfigAdminService/ListRegisteredModels", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceListRegisteredModelsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigAdminService_ListRegisteredModelsClient interface {
	Recv() (*ModelInfo, error)
	grpc.ClientStream
}

type configAdminServiceListRegisteredModelsClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceListRegisteredModelsClient) Recv() (*ModelInfo, error) {
	m := new(ModelInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) GetNetworkChanges(ctx context.Context, in *NetworkChangesRequest, opts ...grpc.CallOption) (ConfigAdminService_GetNetworkChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[2], "/onos.config.admin.ConfigAdminService/GetNetworkChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceGetNetworkChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigAdminService_GetNetworkChangesClient interface {
	Recv() (*NetChange, error)
	grpc.ClientStream
}

type configAdminServiceGetNetworkChangesClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceGetNetworkChangesClient) Recv() (*NetChange, error) {
	m := new(NetChange)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) RollbackNetworkChange(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, "/onos.config.admin.ConfigAdminService/RollbackNetworkChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAdminServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*device1.Snapshot, error) {
	out := new(device1.Snapshot)
	err := c.cc.Invoke(ctx, "/onos.config.admin.ConfigAdminService/GetSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAdminServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (ConfigAdminService_ListSnapshotsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[3], "/onos.config.admin.ConfigAdminService/ListSnapshots", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceListSnapshotsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigAdminService_ListSnapshotsClient interface {
	Recv() (*device1.Snapshot, error)
	grpc.ClientStream
}

type configAdminServiceListSnapshotsClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceListSnapshotsClient) Recv() (*device1.Snapshot, error) {
	m := new(device1.Snapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) CompactChanges(ctx context.Context, in *CompactChangesRequest, opts ...grpc.CallOption) (*CompactChangesResponse, error) {
	out := new(CompactChangesResponse)
	err := c.cc.Invoke(ctx, "/onos.config.admin.ConfigAdminService/CompactChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigAdminServiceServer is the server API for ConfigAdminService service.
type ConfigAdminServiceServer interface {
	// RegisterModel adds the specified YANG model to the list of supported models.
	// There is no unregister because once loaded plugins cannot be unloaded
	RegisterModel(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// UploadRegisterModel uploads and adds the model plugin to the list of supported models.
	UploadRegisterModel(ConfigAdminService_UploadRegisterModelServer) error
	// ListRegisteredModels returns a stream of registered models.
	ListRegisteredModels(*ListModelsRequest, ConfigAdminService_ListRegisteredModelsServer) error
	// GetNetworkChanges returns a stream of network changes submitted via gNMI.
	GetNetworkChanges(*NetworkChangesRequest, ConfigAdminService_GetNetworkChangesServer) error
	// RollbackNetworkChange rolls back the specified network change (or the latest one).
	RollbackNetworkChange(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// GetSnapshot gets a snapshot
	GetSnapshot(context.Context, *GetSnapshotRequest) (*device1.Snapshot, error)
	// ListSnapshots gets a list of snapshots
	ListSnapshots(*ListSnapshotsRequest, ConfigAdminService_ListSnapshotsServer) error
	// CompactChanges requests a snapshot of NetworkChange and DeviceChange stores
	CompactChanges(context.Context, *CompactChangesRequest) (*CompactChangesResponse, error)
}

// UnimplementedConfigAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConfigAdminServiceServer struct {
}

func (*UnimplementedConfigAdminServiceServer) RegisterModel(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterModel not implemented")
}
func (*UnimplementedConfigAdminServiceServer) UploadRegisterModel(srv ConfigAdminService_UploadRegisterModelServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadRegisterModel not implemented")
}
func (*UnimplementedConfigAdminServiceServer) ListRegisteredModels(req *ListModelsRequest, srv ConfigAdminService_ListRegisteredModelsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListRegisteredModels not implemented")
}
func (*UnimplementedConfigAdminServiceServer) GetNetworkChanges(req *NetworkChangesRequest, srv ConfigAdminService_GetNetworkChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNetworkChanges not implemented")
}
func (*UnimplementedConfigAdminServiceServer) RollbackNetworkChange(ctx context.Context, req *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackNetworkChange not implemented")
}
func (*UnimplementedConfigAdminServiceServer) GetSnapshot(ctx context.Context, req *GetSnapshotRequest) (*device1.Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (*UnimplementedConfigAdminServiceServer) ListSnapshots(req *ListSnapshotsRequest, srv ConfigAdminService_ListSnapshotsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (*UnimplementedConfigAdminServiceServer) CompactChanges(ctx context.Context, req *CompactChangesRequest) (*CompactChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompactChanges not implemented")
}

func RegisterConfigAdminServiceServer(s *grpc.Server, srv ConfigAdminServiceServer) {
	s.RegisterService(&_ConfigAdminService_serviceDesc, srv)
}

func _ConfigAdminService_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAdminServiceServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.config.admin.ConfigAdminService/RegisterModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAdminServiceServer).RegisterModel(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAdminService_UploadRegisterModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigAdminServiceServer).UploadRegisterModel(&configAdminServiceUploadRegisterModelServer{stream})
}

type ConfigAdminService_UploadRegisterModelServer interface {
	SendAndClose(*RegisterResponse) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type configAdminServiceUploadRegisterModelServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceUploadRegisterModelServer) SendAndClose(m *RegisterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *configAdminServiceUploadRegisterModelServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ConfigAdminService_ListRegisteredModels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListModelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigAdminServiceServer).ListRegisteredModels(m, &configAdminServiceListRegisteredModelsServer{stream})
}

type ConfigAdminService_ListRegisteredModelsServer interface {
	Send(*ModelInfo) error
	grpc.ServerStream
}

type configAdminServiceListRegisteredModelsServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceListRegisteredModelsServer) Send(m *ModelInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigAdminService_GetNetworkChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NetworkChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigAdminServiceServer).GetNetworkChanges(m, &configAdminServiceGetNetworkChangesServer{stream})
}

type ConfigAdminService_GetNetworkChangesServer interface {
	Send(*NetChange) error
	grpc.ServerStream
}

type configAdminServiceGetNetworkChangesServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceGetNetworkChangesServer) Send(m *NetChange) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigAdminService_RollbackNetworkChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAdminServiceServer).RollbackNetworkChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.config.admin.ConfigAdminService/RollbackNetworkChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAdminServiceServer).RollbackNetworkChange(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAdminService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAdminServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.config.admin.ConfigAdminService/GetSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAdminServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAdminService_ListSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSnapshotsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigAdminServiceServer).ListSnapshots(m, &configAdminServiceListSnapshotsServer{stream})
}

type ConfigAdminService_ListSnapshotsServer interface {
	Send(*device1.Snapshot) error
	grpc.ServerStream
}

type configAdminServiceListSnapshotsServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceListSnapshotsServer) Send(m *device1.Snapshot) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigAdminService_CompactChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAdminServiceServer).CompactChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.config.admin.ConfigAdminService/CompactChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAdminServiceServer).CompactChanges(ctx, req.(*CompactChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.config.admin.ConfigAdminService",
	HandlerType: (*ConfigAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModel",
			Handler:    _ConfigAdminService_RegisterModel_Handler,
		},
		{
			MethodName: "RollbackNetworkChange",
			Handler:    _ConfigAdminService_RollbackNetworkChange_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _ConfigAdminService_GetSnapshot_Handler,
		},
		{
			MethodName: "CompactChanges",
			Handler:    _ConfigAdminService_CompactChanges_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadRegisterModel",
			Handler:       _ConfigAdminService_UploadRegisterModel_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ListRegisteredModels",
			Handler:       _ConfigAdminService_ListRegisteredModels_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNetworkChanges",
			Handler:       _ConfigAdminService_GetNetworkChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSnapshots",
			Handler:       _ConfigAdminService_ListSnapshots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/northbound/admin/admin.proto",
}
