linters:
  enable:
    - gofmt
    - gocyclo
    - golint
    - misspell
    - typecheck
    - errcheck
run:
  skip-dirs:
    - modelplugin

issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `.*Stop` is not checked
  exclude-rules:
    - path: pkg/northbound/gnmi/set.go
      linters:
        - typecheck
