apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  release: "{{ .Release.Name }}"
  heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HTTP_PROXY
              value: $(NODE_NAME):4140
          command:
            - onos-config-manager
          args:
            - "-configStore=/etc/onos-config-manager/test-configs/configStore-sample.json"
            - "-changeStore=/etc/onos-config-manager/test-configs/changeStore-sample.json"
            - "-deviceStore=/etc/onos-config-manager/test-configs/deviceStore-sample.json"
            - "-networkStore=/etc/onos-config-manager/test-configs/networkStore-sample.json"
          readinessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 15
            periodSeconds: 20
          # Mount the test configuration
          # TODO: This should be removed when stores are added!
          volumeMounts:
            - name: test-config
              mountPath: /etc/onos-config-manager/test-configs
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      # Mount test volumes
      # TODO: This should be removed when stores are added!
      volumes:
        - name: test-config
          configMap:
            name: {{ template "fullname" . }}-config