nameOverride: ""

replicas: 3
annotations: {}

image:
  repository: onosproject/device-simulator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi
