// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/types/network/rollback/types.proto

package rollback

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	github_com_onosproject_onos_config_pkg_types "github.com/onosproject/onos-config/pkg/types"
	meta "github.com/onosproject/onos-config/pkg/types/meta"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// NetworkRollback is a configuration for rolling back a NetworkChange
// The NetworkRollback must reference a NetworkChange by its 'id' via the 'change_id' field.
type NetworkRollback struct {
	// 'id' is the ID of the rollback
	ID ID `protobuf:"bytes,1,opt,name=id,proto3,casttype=ID" json:"id,omitempty"`
	// 'index' is the index of the rollback
	Index Index `protobuf:"varint,2,opt,name=index,proto3,casttype=Index" json:"index,omitempty"`
	// 'revision' is the rollback revision number
	Revision Revision `protobuf:"varint,3,opt,name=revision,proto3,casttype=Revision" json:"revision,omitempty"`
	// 'change_id' is a foreign key to the 'id' field of the NetworkChange to rollback
	ChangeID github_com_onosproject_onos_config_pkg_types.ID `protobuf:"bytes,4,opt,name=change_id,json=changeId,proto3,casttype=github.com/onosproject/onos-config/pkg/types.ID" json:"change_id,omitempty"`
	// status is the current status of the rollback
	// The rollback will be initialized with the 'PENDING' status and will progress through the 'APPLYING'
	// status and ultimately marked 'SUCCEEDED' or 'FAILED' once the rollback is complete. If the rollback
	// fails, a 'reason' and optional 'message' will be provided.
	Status meta.Status `protobuf:"varint,5,opt,name=status,proto3,enum=onos.config.meta.Status" json:"status,omitempty"`
	// 'reason' is the reason the rollback failed
	// The 'reason' field will be set to 'ERROR' by default and is invalid unless the 'status' is 'FAILED'.
	Reason meta.FailureReason `protobuf:"varint,6,opt,name=reason,proto3,enum=onos.config.meta.FailureReason" json:"reason,omitempty"`
	// 'message' is an optional status message
	// The message will be empty unless the rollback is failed with a 'FAILED' status, in which case the
	// 'message' field may be used to provide a failure message.
	Message string `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	// 'created' is the time at which the rollback was created
	Created time.Time `protobuf:"bytes,8,opt,name=created,proto3,stdtime" json:"created"`
	// 'updated' is the time at which the rollback was last updated
	Updated time.Time `protobuf:"bytes,9,opt,name=updated,proto3,stdtime" json:"updated"`
}

func (m *NetworkRollback) Reset()         { *m = NetworkRollback{} }
func (m *NetworkRollback) String() string { return proto.CompactTextString(m) }
func (*NetworkRollback) ProtoMessage()    {}
func (*NetworkRollback) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad40ae1561e3aa00, []int{0}
}
func (m *NetworkRollback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkRollback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetworkRollback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetworkRollback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkRollback.Merge(m, src)
}
func (m *NetworkRollback) XXX_Size() int {
	return m.Size()
}
func (m *NetworkRollback) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkRollback.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkRollback proto.InternalMessageInfo

func (m *NetworkRollback) GetID() ID {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NetworkRollback) GetIndex() Index {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *NetworkRollback) GetRevision() Revision {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *NetworkRollback) GetChangeID() github_com_onosproject_onos_config_pkg_types.ID {
	if m != nil {
		return m.ChangeID
	}
	return ""
}

func (m *NetworkRollback) GetStatus() meta.Status {
	if m != nil {
		return m.Status
	}
	return meta.Status_PENDING
}

func (m *NetworkRollback) GetReason() meta.FailureReason {
	if m != nil {
		return m.Reason
	}
	return meta.FailureReason_ERROR
}

func (m *NetworkRollback) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NetworkRollback) GetCreated() time.Time {
	if m != nil {
		return m.Created
	}
	return time.Time{}
}

func (m *NetworkRollback) GetUpdated() time.Time {
	if m != nil {
		return m.Updated
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*NetworkRollback)(nil), "onos.config.network.rollback.NetworkRollback")
}

func init() {
	proto.RegisterFile("pkg/types/network/rollback/types.proto", fileDescriptor_ad40ae1561e3aa00)
}

var fileDescriptor_ad40ae1561e3aa00 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x3f, 0x8f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0xde, 0xb5, 0x4d, 0xcd, 0x09, 0x24, 0x8b, 0xc1, 0xaa, 0x4e, 0x71, 0xc5, 0x80,
	0xb2, 0x60, 0xa3, 0x63, 0x60, 0x02, 0xa4, 0x72, 0x42, 0xea, 0xc2, 0x60, 0x18, 0x91, 0x90, 0x9b,
	0xf8, 0x7c, 0xa6, 0x4d, 0x1c, 0xd9, 0x0e, 0x7f, 0xbe, 0xc5, 0x7d, 0xac, 0x1b, 0x6f, 0x64, 0x21,
	0xa0, 0xf4, 0x5b, 0x74, 0x42, 0x71, 0x12, 0x38, 0xe9, 0xa6, 0x5b, 0xa2, 0x37, 0x8f, 0x9f, 0xdf,
	0xfb, 0x3e, 0xf6, 0x0b, 0x9f, 0x96, 0x5b, 0xc5, 0xfc, 0x8f, 0x52, 0x3a, 0x56, 0x48, 0xff, 0xcd,
	0xd8, 0x2d, 0xb3, 0x66, 0xb7, 0xdb, 0x88, 0x74, 0xdb, 0xc9, 0xb4, 0xb4, 0xc6, 0x1b, 0x74, 0x6a,
	0x0a, 0xe3, 0x68, 0x6a, 0x8a, 0x0b, 0xad, 0x68, 0xef, 0xa4, 0x83, 0x73, 0x41, 0x94, 0x31, 0x6a,
	0x27, 0x59, 0xf0, 0x6e, 0xaa, 0x0b, 0xe6, 0x75, 0x2e, 0x9d, 0x17, 0x79, 0xd9, 0xe1, 0x8b, 0xc7,
	0xca, 0x28, 0x13, 0x4a, 0xd6, 0x56, 0xbd, 0xfa, 0x4a, 0x69, 0x7f, 0x59, 0x6d, 0x68, 0x6a, 0x72,
	0xd6, 0xf6, 0x2f, 0xad, 0xf9, 0x22, 0x53, 0x1f, 0xea, 0x67, 0xdd, 0x2c, 0xf6, 0x3f, 0x5f, 0x2e,
	0xbd, 0xb8, 0x9d, 0xe9, 0xc9, 0xaf, 0x23, 0xf8, 0xe8, 0x7d, 0x17, 0x85, 0xf7, 0x49, 0xd0, 0x29,
	0x1c, 0xeb, 0x0c, 0x83, 0x25, 0x48, 0xe6, 0xab, 0x93, 0xa6, 0x26, 0xe3, 0xf5, 0xf9, 0x21, 0x7c,
	0xf9, 0x58, 0x67, 0x88, 0xc0, 0x89, 0x2e, 0x32, 0xf9, 0x1d, 0x8f, 0x97, 0x20, 0x39, 0x5e, 0xcd,
	0x0f, 0x35, 0x99, 0xac, 0x5b, 0x81, 0x77, 0x3a, 0x4a, 0x60, 0x64, 0xe5, 0x57, 0xed, 0xb4, 0x29,
	0xf0, 0x51, 0xf0, 0x9c, 0x1c, 0x6a, 0x12, 0xf1, 0x5e, 0xe3, 0xff, 0x4e, 0xd1, 0x27, 0x38, 0x4f,
	0x2f, 0x45, 0xa1, 0xe4, 0x67, 0x9d, 0xe1, 0xe3, 0x30, 0xef, 0x4d, 0x53, 0x93, 0xe8, 0x6d, 0x10,
	0xc3, 0x54, 0x76, 0x9f, 0xeb, 0xd1, 0xf5, 0x39, 0x8f, 0xba, 0x8e, 0xeb, 0x0c, 0x3d, 0x87, 0x53,
	0xe7, 0x85, 0xaf, 0x1c, 0x9e, 0x2c, 0x41, 0xf2, 0xf0, 0x0c, 0xd3, 0xdb, 0xef, 0xdf, 0xbe, 0x04,
	0xfd, 0x10, 0xce, 0x79, 0xef, 0x43, 0x2f, 0xe1, 0xd4, 0x4a, 0xe1, 0x4c, 0x81, 0xa7, 0x81, 0x20,
	0x77, 0x89, 0x77, 0x42, 0xef, 0x2a, 0x2b, 0x79, 0xb0, 0xf1, 0xde, 0x8e, 0x30, 0x9c, 0xe5, 0xd2,
	0x39, 0xa1, 0x24, 0x9e, 0xb5, 0xd7, 0xe0, 0xc3, 0x2f, 0x7a, 0x0d, 0x67, 0xa9, 0x95, 0xc2, 0xcb,
	0x0c, 0x47, 0x4b, 0x90, 0x3c, 0x38, 0x5b, 0xd0, 0x6e, 0xcf, 0x74, 0xd8, 0x33, 0xfd, 0x38, 0xec,
	0x79, 0x15, 0x5d, 0xd7, 0x64, 0x74, 0xf5, 0x9b, 0x00, 0x3e, 0x40, 0x2d, 0x5f, 0x95, 0x59, 0xe0,
	0xe7, 0xf7, 0xe1, 0x7b, 0x68, 0x85, 0xaf, 0x9b, 0x18, 0xdc, 0x34, 0x31, 0xf8, 0xd3, 0xc4, 0xe0,
	0x6a, 0x1f, 0x8f, 0x6e, 0xf6, 0xf1, 0xe8, 0xe7, 0x3e, 0x1e, 0x6d, 0xa6, 0xa1, 0xc1, 0x8b, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x41, 0x3b, 0x3d, 0xbe, 0x02, 0x00, 0x00,
}

func (m *NetworkRollback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkRollback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkRollback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Updated, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Updated):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTypes(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x4a
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Created, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Created):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x42
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Reason != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ChangeID) > 0 {
		i -= len(m.ChangeID)
		copy(dAtA[i:], m.ChangeID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChangeID)))
		i--
		dAtA[i] = 0x22
	}
	if m.Revision != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Revision))
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NetworkRollback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.Revision != 0 {
		n += 1 + sovTypes(uint64(m.Revision))
	}
	l = len(m.ChangeID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if m.Reason != 0 {
		n += 1 + sovTypes(uint64(m.Reason))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Created)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Updated)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NetworkRollback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkRollback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkRollback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = ID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= Index(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			m.Revision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Revision |= Revision(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChangeID = github_com_onosproject_onos_config_pkg_types.ID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= meta.Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= meta.FailureReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updated", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Updated, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthTypes
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTypes(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthTypes
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTypes = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes   = fmt.Errorf("proto: integer overflow")
)
