// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/pluginregistry/registry.go

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v2 "github.com/onosproject/onos-api/go/onos/config/v2"
	pluginregistry "github.com/onosproject/onos-config/pkg/pluginregistry"
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
)

// MockModelPluginService is a mock of ModelPluginService interface.
type MockModelPluginService struct {
	ctrl     *gomock.Controller
	recorder *MockModelPluginServiceMockRecorder
}

// MockModelPluginServiceMockRecorder is the mock recorder for MockModelPluginService.
type MockModelPluginServiceMockRecorder struct {
	mock *MockModelPluginService
}

// NewMockModelPluginService creates a new mock instance.
func NewMockModelPluginService(ctrl *gomock.Controller) *MockModelPluginService {
	mock := &MockModelPluginService{ctrl: ctrl}
	mock.recorder = &MockModelPluginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelPluginService) EXPECT() *MockModelPluginServiceMockRecorder {
	return m.recorder
}

// Capabilities mocks base method.
func (m *MockModelPluginService) Capabilities(ctx context.Context) *gnmi.CapabilityResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capabilities", ctx)
	ret0, _ := ret[0].(*gnmi.CapabilityResponse)
	return ret0
}

// Capabilities indicates an expected call of Capabilities.
func (mr *MockModelPluginServiceMockRecorder) Capabilities(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capabilities", reflect.TypeOf((*MockModelPluginService)(nil).Capabilities), ctx)
}

// GetPathValues mocks base method.
func (m *MockModelPluginService) GetPathValues(ctx context.Context, pathPrefix string, jsonData []byte) ([]*v2.PathValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPathValues", ctx, pathPrefix, jsonData)
	ret0, _ := ret[0].([]*v2.PathValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPathValues indicates an expected call of GetPathValues.
func (mr *MockModelPluginServiceMockRecorder) GetPathValues(ctx, pathPrefix, jsonData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPathValues", reflect.TypeOf((*MockModelPluginService)(nil).GetPathValues), ctx, pathPrefix, jsonData)
}

// Validate mocks base method.
func (m *MockModelPluginService) Validate(ctx context.Context, jsonData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, jsonData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockModelPluginServiceMockRecorder) Validate(ctx, jsonData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockModelPluginService)(nil).Validate), ctx, jsonData)
}

// MockPluginRegistry is a mock of PluginRegistry interface.
type MockPluginRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPluginRegistryMockRecorder
}

// MockPluginRegistryMockRecorder is the mock recorder for MockPluginRegistry.
type MockPluginRegistryMockRecorder struct {
	mock *MockPluginRegistry
}

// NewMockPluginRegistry creates a new mock instance.
func NewMockPluginRegistry(ctrl *gomock.Controller) *MockPluginRegistry {
	mock := &MockPluginRegistry{ctrl: ctrl}
	mock.recorder = &MockPluginRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginRegistry) EXPECT() *MockPluginRegistryMockRecorder {
	return m.recorder
}

// GetPlugin mocks base method.
func (m *MockPluginRegistry) GetPlugin(model v2.TargetType, version v2.TargetVersion) (*pluginregistry.ModelPlugin, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlugin", model, version)
	ret0, _ := ret[0].(*pluginregistry.ModelPlugin)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPlugin indicates an expected call of GetPlugin.
func (mr *MockPluginRegistryMockRecorder) GetPlugin(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlugin", reflect.TypeOf((*MockPluginRegistry)(nil).GetPlugin), id)
}

// GetPlugins mocks base method.
func (m *MockPluginRegistry) GetPlugins() []*pluginregistry.ModelPlugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlugins")
	ret0, _ := ret[0].([]*pluginregistry.ModelPlugin)
	return ret0
}

// GetPlugins indicates an expected call of GetPlugins.
func (mr *MockPluginRegistryMockRecorder) GetPlugins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlugins", reflect.TypeOf((*MockPluginRegistry)(nil).GetPlugins))
}

// Start mocks base method.
func (m *MockPluginRegistry) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockPluginRegistryMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPluginRegistry)(nil).Start))
}

// Stop mocks base method.
func (m *MockPluginRegistry) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockPluginRegistryMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPluginRegistry)(nil).Stop))
}
